version: '3.5'
services:
  layer-2a:
    container_name: layer-2a
    image: layer-2a:latest
    env_file:
      - ./deployments/production/database.env
      - ./deployments/production/server.env
    ports:
      - '50055:50055'
    volumes:
      - ./sqlite3/auth.db:/sqlite3/auth.db:rw
    
